# Generated by Django 5.2.10 on 2026-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
